!=======================================================================
! Generated by  : PSCAD v4.5.0.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     E1, RT_1, E2, RT_2, E3, RT_3, E4
      REAL     RT_4, E5, RT_5

! Internal Variables
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 10
      NPGB      = NPGB + 5
      INODE     = NNODE + 2
      NNODE     = NNODE + 7

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 9
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      E1       = STOF(ISTOF + 1)
      RT_1     = STOF(ISTOF + 2)
      E2       = STOF(ISTOF + 3)
      RT_2     = STOF(ISTOF + 4)
      E3       = STOF(ISTOF + 5)
      RT_3     = STOF(ISTOF + 6)
      E4       = STOF(ISTOF + 7)
      RT_4     = STOF(ISTOF + 8)
      E5       = STOF(ISTOF + 9)
      RT_5     = STOF(ISTOF + 10)

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
!  Single Phase AC source: Type: Ideal
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF = NRTCF + 4
      CALL EMTDC_1PVSRC(SS(1), (IBRCH(1)+1),RVD1_4,1,RVD1_1,RVD1_2,RVD1_&
     &3)

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = E1
      STOF(ISTOF + 2) = RT_1
      STOF(ISTOF + 3) = E2
      STOF(ISTOF + 4) = RT_2
      STOF(ISTOF + 5) = E3
      STOF(ISTOF + 6) = RT_3
      STOF(ISTOF + 7) = E4
      STOF(ISTOF + 8) = RT_4
      STOF(ISTOF + 9) = E5
      STOF(ISTOF + 10) = RT_5

!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
      REAL    RMS3          ! 'Instantaneous RMS Measurement'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_1, NT_2, NT_3, NT_4, NT_5

! Control Signals
      REAL     E1, RT_1, E2, RT_2, E3, RT_3, E4
      REAL     RT_4, E5, RT_5

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 5
      INODE     = NNODE + 2
      NNODE     = NNODE + 7

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 9
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      E1       = STOF(ISTOF + 1)
      RT_1     = STOF(ISTOF + 2)
      E2       = STOF(ISTOF + 3)
      RT_2     = STOF(ISTOF + 4)
      E3       = STOF(ISTOF + 5)
      RT_3     = STOF(ISTOF + 6)
      E4       = STOF(ISTOF + 7)
      RT_4     = STOF(ISTOF + 8)
      E5       = STOF(ISTOF + 9)
      RT_5     = STOF(ISTOF + 10)

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)
      NT_2  = NODE(INODE + 2)
      NT_3  = NODE(INODE + 3)
      NT_4  = NODE(INODE + 4)
      NT_5  = NODE(INODE + 5)

!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[voltmeter] Voltmeter (Line - Line) 'E1'
      E1 = EMTDC_VVDC(SS(1), 0, NT_4)

! 20:[rms-inst] Single Phase RMS Meter 
      RT_1 = RMS3( E1 , 0.02 )

! 30:[pgb] Output Channel 'E1'

      PGB(IPGB+1) = RT_1

! 40:[voltmeter] Voltmeter (Line - Line) 'E2'
      E2 = EMTDC_VVDC(SS(1), NT_4, NT_5)

! 50:[rms-inst] Single Phase RMS Meter 
      RT_2 = RMS3( E2 , 0.02 )

! 60:[pgb] Output Channel 'E2'

      PGB(IPGB+2) = RT_2

! 70:[voltmeter] Voltmeter (Line - Line) 'E3'
      E3 = EMTDC_VVDC(SS(1), NT_5, NT_3)

! 80:[voltmeter] Voltmeter (Line - Line) 'E4'
      E4 = EMTDC_VVDC(SS(1), NT_3, NT_2)

! 90:[voltmeter] Voltmeter (Line - Line) 'E5'
      E5 = EMTDC_VVDC(SS(1), NT_2, NT_1)

! 100:[rms-inst] Single Phase RMS Meter 
      RT_3 = RMS3( E3 , 0.02 )

! 110:[rms-inst] Single Phase RMS Meter 
      RT_4 = RMS3( E4 , 0.02 )

! 120:[rms-inst] Single Phase RMS Meter 
      RT_5 = RMS3( E5 , 0.02 )

! 130:[pgb] Output Channel 'E5'

      PGB(IPGB+3) = RT_5

! 140:[pgb] Output Channel 'E4'

      PGB(IPGB+4) = RT_4

! 150:[pgb] Output Channel 'E3'

      PGB(IPGB+5) = RT_3

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = E1
      STOF(ISTOF + 2) = RT_1
      STOF(ISTOF + 3) = E2
      STOF(ISTOF + 4) = RT_2
      STOF(ISTOF + 5) = E3
      STOF(ISTOF + 6) = RT_3
      STOF(ISTOF + 7) = E4
      STOF(ISTOF + 8) = RT_4
      STOF(ISTOF + 9) = E5
      STOF(ISTOF + 10) = RT_5

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 7

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 9
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
      CALL E_1PVSRC_CFG(1,0,6,57.735,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.05)

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_1, NT_2, NT_3, NT_4, NT_5

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 7

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 9
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)
      NT_2  = NODE(INODE + 2)
      NT_3  = NODE(INODE + 3)
      NT_4  = NODE(INODE + 4)
      NT_5  = NODE(INODE + 5)

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 20:[rms-inst] Single Phase RMS Meter 

! 30:[pgb] Output Channel 'E1'

! 50:[rms-inst] Single Phase RMS Meter 

! 60:[pgb] Output Channel 'E2'

! 100:[rms-inst] Single Phase RMS Meter 

! 110:[rms-inst] Single Phase RMS Meter 

! 120:[rms-inst] Single Phase RMS Meter 

! 130:[pgb] Output Channel 'E5'

! 140:[pgb] Output Channel 'E4'

! 150:[pgb] Output Channel 'E3'

      RETURN
      END

